# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d38f9cb8b5637367e01ab9ff65adf951a7b088a0d83dc3b3b583f660bdd446519c076cb6bf19e0ec8c733842f6012b38e8e93aa900c52432aec7b034eff1d9a

test:
  secret_key_base: a3f66f31524bf8cebb042bfe8012d1cba76304ebb6c0ffdac9b1d1fe37f2075281025438bcb0fb526703b997d53e246c91bd5e7c2c382e6d999acd4985bbc4e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
